//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZivBackendSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIMLogTable
    {
        public string DATETIME { get; set; }
        public string ServiceName { get; set; }
        public string RequestId { get; set; }
        public string IpAddress { get; set; }
        public string OperationName { get; set; }
        public string Method { get; set; }
        public string Url { get; set; }
        public string UserEmail { get; set; }
        public string DeploymentRegion { get; set; }
        public string RequestBody { get; set; }
        public string PartitionId { get; set; }
        public string EventEnqueuedUtcTime { get; set; }
        public string EventProcessedUtcTime { get; set; }
        public int Id { get; set; }
    }
}
