//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZivBackendSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZivAPIMGameSystem_dbEntities : DbContext
    {
        public ZivAPIMGameSystem_dbEntities()
            : base("name=ZivAPIMGameSystem_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APIMLogTable> APIMLogTable { get; set; }
        public virtual DbSet<CategoryTable> CategoryTable { get; set; }
        public virtual DbSet<QuestionResultsLogsTable> QuestionResultsLogsTable { get; set; }
        public virtual DbSet<QuestionTable> QuestionTable { get; set; }
        public virtual DbSet<TestTable> TestTable { get; set; }
        public virtual DbSet<UserDetailsTable> UserDetailsTable { get; set; }
    }
}
