//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZivBackendSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionTable
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ImageLocation { get; set; }
        public Nullable<int> QuestionLevel { get; set; }
        public Nullable<int> QuestionPoints { get; set; }
    }
}
